@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

# RECADOS
###
GET {{baseUrl}}/recados?limit=20
Authorization: Bearer {{authToken}}
###
GET {{baseUrl}}/recados/15
###
POST {{baseUrl}}/recados
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Recado",
    "paraId": 8
}
###
PATCH  {{baseUrl}}/recados/15
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Este é um recado de teste",
    "lido": true
}
###
DELETE {{baseUrl}}/recados/14
Authorization: Bearer {{authToken}}


# Pessoas
###
GET {{baseUrl}}/pessoas
Authorization: Bearer {{authToken}}
###
GET {{baseUrl}}/pessoas/1
###
POST {{baseUrl}}/pessoas
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "email": "guis2@email.com",
    "password": "123456",
    "nome": "Guis",
    "routePolicies": ["findAllRecados", "createPessoa", "createRecado"]
}
###
DELETE {{baseUrl}}/pessoas/11
Authorization: Bearer {{authToken}}
###
PATCH {{baseUrl}}/pessoas/11
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "password": "123456"
}

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico


# Auth
### Login
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "guis2@email.com",
    "password": "123456"
}


### Re-Autenticação
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}
